spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 
    username: 
    password: 
  data:
    mongodb:
      uri: 

  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
  ai:
    dashscope:
              api-key: 
              base-url: 
              chat:
                options:
                  model: qwen-plus

aliyun:
  oss:
    endpoint: oss-cn-beijing..com
    access-key-id: 
    access-key-secret: 
    bucket-name: 
    base-dir: 
    base-vio: 


mybatis:
  mapper-locations: classpath*:com/example/XSJ/Mapper/UserMapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

email:
  sender:
    #邮箱账号
    username:
    auth-code: 
  smtp :
    host: smtp.qq.com
    port: 465
    ssl : true
    debug: true


