spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 
    username: 
    password: 
  data:
    mongodb:
      uri: 

  mvc:
    format:
      date-time: 
    dashscope:
              api-key: 
              base-url: 
              chat:
                options:
                  model:

aliyun:
  oss:
    endpoint:
    access-key-id: 
    access-key-secret: 
    bucket-name: 
    base-dir: 
    base-vio: 


mybatis:
  mapper-locations:
  configuration:
    map-underscore-to-camel-case: true

email:
  sender:
    #邮箱账号
    username:
    auth-code: 
  smtp :
    host:
    port:
    ssl :
    debug:


